# Generated by Django 4.2 on 2023-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_trigram_smilarity_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
